// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_math from "rescript/lib/es6/js_math.js";

function isOk(param) {
  return true;
}

function rollDiceWith6Sides(param) {
  return Js_math.random_int(6, 6);
}

export {
  isOk ,
  rollDiceWith6Sides ,
  
}
/* No side effect */
