// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "@dusty-phillips/rescript-zora/src/Zora.mjs";
import * as Zora$1 from "zora";
import * as Setup from "./Setup.mjs";

Zora$1.test("WHEN SETUP UNIT TESTING WITH ZORA", (function (t) {
        t.test("THEN setup is fine", (function (t) {
                var r = Setup.isOk(undefined);
                t.ok(r, "is ok");
                return Zora.done(undefined);
              }));
        
      }));

Zora$1.test("WHEN SETUP UNIT TESTING WITH ZORA", (function (t) {
        t.test("THEN result is an integer between 1 and 6", (function (t) {
                var r = Setup.rollDiceWith6Sides(undefined);
                t.equal(r >= 1, true, "greater than or equals to 1");
                t.equal(r <= 6, true, "lesser than or equals to 6");
                return Zora.done(undefined);
              }));
        
      }));

export {
  
}
/*  Not a pure module */
